### ISSUE TITLE
Google Embedding

### ISSUE THREAD

**Issue by loginatcode** [benbrandt/text-splitter#103]
**Is your feature request related to a problem? Please describe.**
No, however, i thought to check if there's any chunks procedure already create for Google Gemini model embedding-001

**Comment by benbrandt** [comment]
Nope no usage of the Gemini models currently

**Comment by benbrandt** [comment]
How do they do the tokenization? If it is via the hugging face library then yes it would work

**Comment by benbrandt** [comment]
@loginatcode I will close this for now since I haven't heard back. Looking at the Google docs, it seems like they have some custom way of getting the number of tokens. You could do this in Rust by doing a custom impl of `ChunkSizer`, or in Python by using the `from_callback` method on either of the Splitters. 

Hopefully that helps, and feel free to respond if this doesn't answer your question.
