### ISSUE TITLE
Not working with certain tokenizer(s)

### ISSUE THREAD

**Issue by xtfocus** [benbrandt/text-splitter#129]
**Describe the bug**
The library works fine with `google-bert/bert-base-cased` but with `thenlper/gte-small` (and maybe others), it shows weird calculation output: the encoded output is always 128 in length, etc.

**To Reproduce Tokenizer not working with `gte-small`**
```python
from semantic_text_splitter import TextSplitter
from tokenizers import Tokenizer

text = """
This is an example text This is an example text
"""

model_name = "thenlper/gte-small" # limit 512 tokens

max_tokens = 300 # Modify this to 5 tokens also lead to weird output with 3-chars chunks
tokenizer = Tokenizer.from_pretrained(model_name)
splitter = TextSplitter.from_huggingface_tokenizer(tokenizer, trim_chunks=False)

chunks = splitter.chunks(text, max_tokens)

print("Number of chunks =", len(chunks))
for i,v in enumerate(chunks):
    print(f"CHUNK {i}, length={len(tokenizer.encode(v))} tokens, {len(v)} chars")
    print(v)
```
Will produce just one chunk with number of tokens = 128. Feel free to replace the text with a longer one, the issue insists.

I included the sample [notebook](https://colab.research.google.com/drive/1ARPtxRbpU2dfo9JS9roelyqqpHdRN6vv?usp=sharing) to reproduce.

**Comment by benbrandt** [comment]
@xtfocus thanks for reporting. It seems that this tokenizer does some padding, which is why it is always at 128, but I am also seeing some repeated chunks, which is odd...

I will definitely dig in and see what I can find out. I'll see if there is a fix, or if there needs to be some extra documentation at the very least because I can definitely see a problem for any tokenizer that uses padding.

**Comment by benbrandt** [comment]
Hi @xtfocus the fix for this was release in https://github.com/benbrandt/text-splitter/releases/tag/v0.9.0

Hope this helps!
