### ISSUE TITLE
Compilation Error when using TextSplitter

### ISSUE THREAD

**Issue by santiagomed** [benbrandt/text-splitter#62]
**Describe the bug**
Hi @benbrandt I randomly started getting a compilation error when using `TextSplitter::new(tokenizer).with_trim_chunks()` due to it not implementing `ChunkSizer`. Where there any changes recently on a dependency?

**To Reproduce**
```rust
let tokenizer = match tokenizer {
    Tokenizer::Huggingface(tokenizer) => {
        tokenizers::Tokenizer::from_pretrained(tokenizer, None).map_err(anyhow::Error::msg)?
    }
    Tokenizer::File(path) => tokenizers::Tokenizer::from_file(path).map_err(anyhow::Error::msg)?,
    Tokenizer::Bytes(bytes) => tokenizers::Tokenizer::from_bytes(bytes).map_err(anyhow::Error::msg)?,
};

let splitter = TextSplitter::new(tokenizer).with_trim_chunks(true);
```
Compilation error:
```rust
note: required by a bound in `TextSplitter::<S>::new`
   --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/text-splitter-0.4.5/src/lib.rs:301:8
    |
301 |     S: ChunkSizer,
    |        ^^^^^^^^^^ required by this bound in `TextSplitter::<S>::new`
...
312 |     pub fn new(chunk_sizer: S) -> Self {
    |            --- required by a bound in this associated function

error[E0599]: the method `with_trim_chunks` exists for struct `TextSplitter<Tokenizer>`, but its trait bounds were not satisfied
   --> orca/src/record/mod.rs:151:53
    |
151 |         let splitter = TextSplitter::new(tokenizer).with_trim_chunks(true);
    |                                                     ^^^^^^^^^^^^^^^^ method cannot be called on `TextSplitter<Tokenizer>` due to unsatisfied trait bounds
    |
   ::: /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokenizers-0.14.1/src/tokenizer/mod.rs:403:1
    |
403 | pub struct Tokenizer(
    | -------------------- doesn't satisfy `tokenizers::Tokenizer: ChunkSizer`
    |
    = note: the following trait bounds were not satisfied:
            `tokenizers::Tokenizer: ChunkSizer`

error[E0277]: the trait bound `tokenizers::Tokenizer: ChunkSizer` is not satisfied
   --> orca/src/record/mod.rs:151:24
    |
151 |         let splitter = TextSplitter::new(tokenizer).with_trim_chunks(true);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ChunkSizer` is not implemented for `tokenizers::Tokenizer`
    |
    = help: the following other types implement trait `ChunkSizer`:
              Characters
              tiktoken_rs::vendor_tiktoken::CoreBPE
              tokenizers::tokenizer::Tokenizer
              &tokenizers::tokenizer::Tokenizer
              &tiktoken_rs::vendor_tiktoken::CoreBPE
note: required by a bound in `TextSplitter`
   --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/text-splitter-0.4.5/src/lib.rs:283:8
    |
281 | pub struct TextSplitter<S>
    |            ------------ required by a bound in this struct
282 | where
283 |     S: ChunkSizer,
    |        ^^^^^^^^^^ required by this bound in `TextSplitter`
```

**Desktop (please complete the following information):**
 - OS: MacOS Arm64

**Comment by benbrandt** [comment]
Hi @santiagomed thanks for reporting. This usually happens if two versions of the `tokenizers` crate are present. 

I purposely have the version range to be `>=0.13.3, <0.16.0` so that it would allow the user to specify their own version, but testing this out myself I see that if I pin `tokenizers` to `0.14.1` that I do indeed get both `0.14.1` and `0.15.0` installed, which isn't what I intended. I'll have to look at if there is a better way to allow the user to bring their own version of the `tokenizers` crate, because I would like to support whichever version the user is using.

**Comment by benbrandt** [comment]
@santiagomed ok it seems that the dependency resolution doesn't behave like i thought it does.

An immediate fix would be to run
```
cargo update -p tokenizers@0.15.0 --precise 0.14.1
```

But I may need to start releasing major versions every time one of these dependencies releases a major version

**Comment by benbrandt** [comment]
@santiagomed just to let you know, I've started, as of the v0.5.0 release today, to stick to a major version number for each tokenizer. I think in order to actually support multiple, I'd need to make it opt-in features for each major version of the tokenizers. 

This may be what I do going forward, but hopefully this makes things clearer in the future.

Let me know if you run into any more issues. Thanks for reporting, and using this crate in `orca`! By the way the new release comes with some nice performance improvements when used with tokenizers, so hopefully it helps you out in your use case too!
