### ISSUE TITLE
Tokenizers Example doesn't run + `from_pretrained` from the tokenizers crate needs features=["http"]

### ISSUE THREAD

**Issue by SimonCW** [benbrandt/text-splitter#89]
Hey @benbrandt, 
thanks for your effort with text-splitter! I found a small bug and added a PR to fix.

**Describe the bug**
Running the tokenizers example doesn't work. As I see it, there are two problems.
1. The tokenizers crate is not exposed, so it must be installed by the user directly to be used.
2. It must be installed with the "http" feature enabled to use `from_pretrained()`.

**To Reproduce**
Install via 
 ```toml
text-splitter = { version = "0.6.0", features = ["tokenizers"] }
```
Then run the example from the Readme
```rust
use text_splitter::TextSplitter;
// Can also use anything else that implements the ChunkSizer
// trait from the text_splitter crate.
use tokenizers::Tokenizer;

let tokenizer = Tokenizer::from_pretrained("bert-base-cased", None).unwrap();
let max_tokens = 1000;
let splitter = TextSplitter::new(tokenizer)
    // Optionally can also have the splitter trim whitespace for you
    .with_trim_chunks(true);

let chunks = splitter.chunks("your document text", max_tokens);
```

**Expected behavior**
Working example. I fixed by adding tokenizers as a direct dependency
```rust
tokenizers = { version = "0.15.1", features = ["http"] }
```

**Comment by SimonCW** [comment]
I created a PR with a fix here: https://github.com/benbrandt/text-splitter/pull/90

**Comment by benbrandt** [comment]
@SimonCW good point! 

However, I wonder if this should be solved by better documentation on how to use this with other crates (which admittedly there isn't really any)

The reason the `http` feature isn't enabled is because it brings in a lot of extra dependencies that aren't necessary if you are loading tokenizers from files. 

Since I am just implementing a trait for the tokenizer crate, I tried to be as minimal as their crate would let me (unfortunately I have to choose one of two regex features, which means I am kind of blocked from enabling wasm `tokenizers` usage... But I digress...) And let the user of the crate decide how they want to use the `tokenizers` crate themselves. 

Since Rust requires you to either own the trait or the struct to `impl Trait`, I am doing the bridge between the two crates, but I don't actually want to own the tokenizers crate for the user. 

Does that make sense? Regardless, I think I need clearer documentation. And the fix you specified is exactly as intended.

**Comment by SimonCW** [comment]
Makes 100% sense to me! I see two options:

### 1. Re-exposing tokenizers features
We could add a feature `tokenizers-http` which then uses tokenizers = {..., features = ["http"]} as dependency. In the README example we could "guard" the use of `from_pretrained()` with a `#[cfg(features="tokenizers-http"]`, analogous to the tokenizers README (https://github.com/huggingface/tokenizers/blob/main/tokenizers/README.md#loading-a-pretrained-tokenizer-from-the-hub). However, where do we stop? Do we need to re-expose other features as well?

### 2. Adding example cargo.toml to README
We could require the user to specify tokenizers as a direct dependency like I did in my initial post. To document we could simply add an expandable code block with an exemplary cargo.toml. See, for example, serde: https://github.com/serde-rs/serde?tab=readme-ov-file#serde-in-action

Based on your goals, to keep dependencies slim, I think 2. would be preferable. Let me know what you think and I'll adapt the PR. However, also keep in mind that specifying tokenizers as a direct dependency compiles tokenizers twice. Once as transitive dependency, once as direct one. Thats at least how I interpret my cargo.lock file.

**Comment by benbrandt** [comment]
Hmm yes 2 would be preferred, and I don't see why this would mean compiling tokenizers twice, but this would not be the first time I am quite surprised by Cargo behavior. 

But because at least in one other app I've seen, the tokenizers crate is not only used for splitting text, I would be very hesitant to take control of the dependency for the user, as I stated earlier. I don't want to be the one reexposing it if I can help it. 

Would be curious to learn from your setup how this is getting compiled twice. When I've seen this in the past, you usually get a compile error because there are two versions of the tokenizers crate, and the trait is only implemented for one and not the other, so there can only be one. But like I said, I would not be surprised if you know something I don't here, so I am happy to learn!

**Comment by SimonCW** [comment]
I updated the README in a new PR and closed the old one. 

Concerning double compilation: That was my mistake and I'm doing the learning (relatively new to Rust). I also had `fastembed` in my dependencies which relies on an older version of `tokenizers`. That's where the second `tokenizers` compilation came from.

**Comment by benbrandt** [comment]
Awesome thank you! And no worries at all, I have been using Rust for awhile, but still am surprised from time to time by cargo behavior, so I didn't want to assume 😆

I'll get your PR merged, and hopefully the crate is helpful to you! I would love to take a look at how you are using it if it is public.

**Comment by SimonCW** [comment]
Awesome, I could look into a small Github Action for running unit tests if that's something you'd want?  I'll probably need it for one of my projects anyway. 

Off-topic:
@benbrandt, your crate was super helpful and a pleasure to use after the crazyness that is langchain 😵‍💫! Unfortunately, I don't really have a project to share. I'm just exploring the LLM-RAG space with Rust to gauge potential for local / self-hosted applications for some of our customers (working for a consultancy that's also partnering with aleph alpha btw 😉 ).

**Comment by benbrandt** [comment]
@SimonCW CI should already be setup, feel free to take a look: https://github.com/benbrandt/text-splitter/blob/main/.github/workflows/ci.yml#L25

And I'm glad to hear! I know it's not perfect, and I have several features I still want to build out, but I also agree about Langchain. One of my motivations for writing this in my spare time 😆
